services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hanania-catalog-app
    container_name: hanania-catalog-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - hanania-network

  web:
    image: nginx:alpine
    container_name: hanania-catalog-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - hanania-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: hanania-catalog-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-hanania_db}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-hanania_user}
    volumes:
      - dbdata:/var/lib/mysql
    # ports:
    #  - "3306:3306"
    networks:
      - hanania-network

networks:
  hanania-network:
    driver: bridge

volumes:
  dbdata:
